baseURL = "https://blog.kerfume.me/"
title = "くらげ.log"
theme = "geekdoc"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

enableGitInfo = true
timeout = 180000

# [taxonomies]
#   tag = "tags"
# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocToC = 3
  geekdocSearch = true